### ISSUE TITLE
Error 001-001

### ISSUE THREAD

**Issue by Shallow1337** [justMaku/gpghax#10]
Did I just brick my Console?

Tried as said in here and even follow up some youtube videos...
Mine as the follow error on boot:

Failed to load data.
Error Code:001-001

Tried to boot with and without the usb drive, still the same error given to me.
Thanks

**Comment by Shallow1337** [comment]
Okey, so reporting in again

Managed to solve the issue by formating the pen, and put again the blank files from the gpghax. The system boot with the "custom21". Unpluged the system from the power, remove the usb, pluged the console back again and everything is back to it's normal format as brand new!

**Comment by justMaku** [comment]
This error occurs when the database file is missing or corrupted, in case anyone else encounters it, please follow the instructions from https://github.com/justMaku/gpghax/issues/18#issuecomment-445759173 to restore the factory database.
