### ISSUE TITLE
Change display

### ISSUE THREAD

**Issue by guzmanfernandez39** [justMaku/gpghax#13]
I accidentally changed settings from OpenGL to SDL window for a game. And it no longer displays even though it’s sound plays. How can I revert the setting?

**Comment by guzmanfernandez39** [comment]
Figured it out. Had to copy the pcsx config file for that game to the usb using lolhack. Edit it in the pc changing video mode from 0 (SDL window) to 1 (OpenGL). Then copy back to ps1.

**Comment by justMaku** [comment]
Thanks for writing it down for other users. Marking as closed.
