### ISSUE TITLE
Restore console

### ISSUE THREAD

**Issue by Pierinolartista** [justMaku/gpghax#14]
It's possible to restore the Playstation classic before the hack? I reset it but shows a transparent tile on the wheel.

**Comment by raimuse** [comment]
Try taking the power cord off and then back again once the consolé is off

**Comment by Pierinolartista** [comment]
I did it but nothing.

**Comment by raimuse** [comment]
If not in the consolé setting restore all but it will delete any Save

**Comment by Pierinolartista** [comment]
I deleted all save and did hard reset too, but nothing.

**Comment by justMaku** [comment]
Remove the custom game from the database and plug the usb into the console, it should remove any modifications

**Comment by poopdawg27** [comment]
> Remove the custom game from the database and plug the usb into the console, it should remove any modifications

I am also having problems removing the empty "Custom Game" frame from my PS Classic menu, could you please tell us exactly how to remove the custom game from the database, I don't know if that means remove the database file itself or text within the "custom.db" file, or the game folder itself, im not sure what to remove. I just want the empty frame gone, the hack didn't work for me.

**Comment by alucard73** [comment]
you delete in line 24 in DISC 24 and line 21 in GAME, you put your USB in the console, the green LED flashes with the orange is that it reads the modifications and you will have your 20 games again and the one you put on will be completely gone.

You say it did not work, did you put in the name of your * .bin? (ex: your game is called resident evil.cue and resident evil.bin but for the playstation classic in the folder 21 you will rename the files in SLUS-94456, you must edit the * .cue to also put SLUS-94456 to the resident evil.bin place)

**Comment by hempknight420x** [comment]
perhaps a step by step because youre instructions arent making any sense. im encountering the same issue as well and i am now unable to access the emulator menu. also when i first tried when it was working. seems like the games werent being read by the ps classic

**Comment by poopdawg27** [comment]
> you delete in line 24 in DISC and line 21 in GAME, you put your USB in the console, the green LED flashes with the orange is that it reads the modifications and you will have your 20 games again and the one you put on will be completely gone.
> 
> You say it did not work, did you put in the name of your * .bin? (ex: your game is called resident evil.cue and resident evil.bin but for the playstation classic in the folder 21 you will rename the files in SLUS-94456, you must edit the * .cue to also put SLUS-94456 to the resident evil.bin place)

Thank you! This fixed the issue, it resolved the "Custom Game" empty frame on the main menu. Here is exactly how to do it:
I used DB Browser for SQLite and opened the Custom DB file and i navigated to the DISC and Game browse screens, from there you do exactly like he said.

**Comment by dimagiba** [comment]
I knew there were risks when I tried this out on my Japanese PS Classic.  Loading and playing custom games work as they have been described but I lost all the built-in games.  I can still cycle through the 20 original titles but the game images are gone.  Nothing happens when I try to play the original games.  I suspect that this has something to do with the list of games written in the custom.db files - they're for the US version of the PS Classic.

I was able to open the custom.db file and indeed it lists the US games.  Does anyone know how to restore the Japanese version of the PS Classic?  Thanks.

**Comment by justMaku** [comment]
If your console is from different region than EU and after installing this you ended up with EU games only, please follow the instruction from https://github.com/justMaku/gpghax/issues/18#issuecomment-445759173 to restore the factory database.

**Comment by hempknight420x** [comment]
so....i did what you guys said. deleted the appropriate lines in game and disc and now my console is bricked. starts up but ends up on error screen. telling me to unplug ac adapter but does nothing of course. any help would be appreciated.
