### ISSUE TITLE
doesn't blink no matter how many times i try

### ISSUE THREAD

**Issue by LucidCubeX** [justMaku/gpghax#16]
i tried everything and the power light doesn't blink at all it stays green i followed every instruction and even looked at every video out the usb is blinking red which means it works but the green light just doesn't blink and it doesn't show custom game.. help

**Comment by blackbadsanta** [comment]
Same here

**Comment by jaricma** [comment]
i think only works with USB 2.0

**Comment by Tucker2015** [comment]
> i think only works with USB 2.0

I have a USB3 key working fine.

**Comment by Matteoson** [comment]
Make sure your USB is formatted as FAT32

**Comment by abe1007** [comment]
I’ve got the same issue. My console is HK/Japanese version.

**Comment by LucidCubeX** [comment]
so i did that to begin with and my usb is a usb 2.0 as well therefore it should work right? nah it still don't work anybody from Australia have this problem too?

**Comment by justMaku** [comment]
Make sure USB drive is named `SONY` and formatted as FAT32
