### ISSUE TITLE
Pre-installed games not working

### ISSUE THREAD

**Issue by Pierinolartista** [justMaku/gpghax#20]
I do not know why, but the pre-installed games no longer start. I deleted everything from the usb and reinstalled the files without success. How can I fix it?

**Comment by justMaku** [comment]
What region is your console from? I'm currently working on redoing the tool and fixing all the issues that might have occurred with the first version.

**Comment by Pierinolartista** [comment]
It is European version. I can't access original games now,not start. I hope you can help me.

**Comment by justMaku** [comment]
Do all of the games stopped working? This is not normal and I'm not sure what could cause this.

**Comment by Pierinolartista** [comment]
Yeah , not started all 20 pre-owned :(

**Comment by justMaku** [comment]
Follow the instructions from https://github.com/justMaku/gpghax/issues/7#issuecomment-445762904 and upload the results here.

**Comment by Pierinolartista** [comment]
[filelist.log](https://github.com/justMaku/gpghax/files/2664950/filelist.log)

**Comment by justMaku** [comment]
Edit `lolhack.sh` to look like this, and run the payload, it should fix this.

```
#!/bin/sh
rm /gaadata/1/1
rm /gaadata/2/2
rm /gaadata/3/3
rm /gaadata/4/4
rm /gaadata/5/5
rm /gaadata/6/6
rm /gaadata/7/7
rm /gaadata/8/8
rm /gaadata/9/9
rm /gaadata/10/10
rm /gaadata/11/11
rm /gaadata/12/12
rm /gaadata/13/13
rm /gaadata/14/14
rm /gaadata/15/15
rm /gaadata/16/16
rm /gaadata/17/17
rm /gaadata/18/18
rm /gaadata/19/19
rm /gaadata/20/20
```

For the future: don't add games with IDs lower than 21

**Comment by Pierinolartista** [comment]
Thanks but what mean "For the future: don't add games with IDs lower than 21" ?

**Comment by justMaku** [comment]
You seem to have created folders 1, 2, 3, 4 etc in games directory, whereas you're supposed to create 21, 22, 23 etc.

**Comment by Pierinolartista** [comment]
I didn't create more folder but just one "22" and cancelled after because not working. Now I have only "21" folder and charge the iso with emulator.

**Comment by Badabingsta** [comment]
I think I have bricked my system can 1 you guys help at all?

**Comment by justMaku** [comment]
@Pierinolartista use the payload I gave you in the previous link.

@Badabingsta create new issue please.

**Comment by Pierinolartista** [comment]
Ok I fix it, now can I use payload to access the emulator?

**Comment by justMaku** [comment]
@Pierinolartista use BleemSync or another project, do not use `gpghax` it was never intended to be used by end-users and is causing a lot of issues.
