### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Badabingsta** [justMaku/gpghax#22]
I may have bricked my console can I reset it to factory setting? It's a UK console!

**Comment by Badabingsta** [comment]
I keep getting the error 

"An error has occured.
Turn off the console, unplug the AC adaptor, and then turn on the console again."

**Comment by justMaku** [comment]
Did you modify the database file? If so, can you try redownloading everything and trying once again, without adding any custom games?

**Comment by Badabingsta** [comment]
I did modify the database file Reyes to add games! Then I removed custom game on the database file and tried again and the error keeps coming up!? Is there no way to reset it to factory settings?

**Comment by justMaku** [comment]
Did you try running the payload again? Make sure all of the files are correctly copied, also, try with another USB drive, some are incompatible.

**Comment by Badabingsta** [comment]
Shall I re download the file and try it on a new usb?

**Comment by justMaku** [comment]
Yes.

**Comment by Badabingsta** [comment]
This has worked perfectly thank you very much for all the work you do.
