### ISSUE TITLE
Default games won't load

### ISSUE THREAD

**Issue by titaniuml** [justMaku/gpghax#23]
Hi mate.  Thanks for the hack.  I've been playing my games fine but yesterday for some reason my default games that came with the classic don't load anymore.  Any idea why?

**Comment by justMaku** [comment]
Follow the steps from: https://github.com/justMaku/gpghax/issues/20#issuecomment-445982511 and stop using gpghax, use Bleemsync instead.

**Comment by titaniuml** [comment]
Ok will do thanks.  Do I just load it once, and once they work, switch off console and remove the script?  Just a one time thing?

And I will use bleem thanks.

**Comment by justMaku** [comment]
Yes, you load the script once, and then remove any trace of gpghax from your USB. Sorry for the trouble.

**Comment by titaniuml** [comment]
No worries mate all done.  Still thanks for your efforts.  All the best with your future stuff.
