### ISSUE TITLE
No Original Games Work 

### ISSUE THREAD

**Issue by ValionPride** [justMaku/gpghax#24]
After editing the custom.db file to remove game 21 from the system, none of the pre-installed games will start. Is there anything I can do to correct this issue?  Thank you,

Tried running the un-install script, I can see the menu of the pre-installed games, but none of the launch.
 
I have included the uninstall file:

Restored default DB
Checking wrong symlinks for game 1
Nothing wrong with game 
1, continuing
Checking wrong symlinks for game 2
Nothing wrong with game 
2, continuing
Checking wrong symlinks for game 3
Nothing wrong with game 
3, continuing
Checking wrong symlinks for game 4
Nothing wrong with game 
4, continuing
Checking wrong symlinks for game 5
Nothing wrong with game 
5, continuing
Checking wrong symlinks for game 6
Nothing wrong with game 
6, continuing
Checking wrong symlinks for game 7
Nothing wrong with game 
7, continuing
Checking wrong symlinks for game 8
Nothing wrong with game 
8, continuing
Checking wrong symlinks for game 9
Nothing wrong with game 
9, continuing
Checking wrong symlinks for game 10
Nothing wrong with game 
10, continuing
Checking wrong symlinks for game 11
Nothing wrong with game 
11, continuing
Checking wrong symlinks for game 12
Nothing wrong with game 
12, continuing
Checking wrong symlinks for game 13
Nothing wrong with game 
13, continuing
Checking wrong symlinks for game 14
Nothing wrong with game 
14, continuing
Checking wrong symlinks for game 15
Nothing wrong with game 
15, continuing
Checking wrong symlinks for game 16
Nothing wrong with game 
16, continuing
Checking wrong symlinks for game 17
Nothing wrong with game 
17, continuing
Checking wrong symlinks for game 18
Nothing wrong with game 
18, continuing
Checking wrong symlinks for game 19
Nothing wrong with game 
19, continuing
Checking wrong symlinks for game 20
Nothing wrong with game 
20, continuing
Checking wrong symlinks for game 21
Nothing wrong with game 
21, continuing
Checking wrong symlinks for game 22
Nothing wrong with game 
22, continuing
Checking wrong symlinks for game 23
Nothing wrong with game 
23, continuing
Checking wrong symlinks for game 24
Nothing wrong with game 
24, continuing
Checking wrong symlinks for game 25
Nothing wrong with game 
25, continuing

Filelist:
/gaadata
/gaadata/5
/gaadata/5/pcsx.cfg
/gaadata/5/5
/gaadata/5/SLES-00032.otf
/gaadata/5/SLES-00032.cue
/gaadata/5/SLES-00032.bin
/gaadata/5/SLES-00032.png
/gaadata/5/SLES-00032.lic
/gaadata/1
/gaadata/1/pcsx.cfg
/gaadata/1/1
/gaadata/1/SCES-00002.lic
/gaadata/1/SCES-00002.cue
/gaadata/1/SCES-00002.png
/gaadata/1/SCES-00002.bin
/gaadata/plugins
/gaadata/14
/gaadata/14/pcsx.cfg
/gaadata/14/SLUS-00797.cue
/gaadata/14/14
/gaadata/14/SLUS-00797.bin
/gaadata/14/SLUS-00797.png
/gaadata/14/SLUS-00797.lic
/gaadata/21
/gaadata/lost+found
/gaadata/databases
/gaadata/databases/regional.db
/gaadata/17
/gaadata/17/pcsx.cfg
/gaadata/17/SCES-01237.bin
/gaadata/17/SCES-01237.lic
/gaadata/17/17
/gaadata/17/SCES-01237.cue
/gaadata/17/SCES-01237.png
/gaadata/4
/gaadata/4/pcsx.cfg
/gaadata/4/SCUS-94163.lic
/gaadata/4/4
/gaadata/4/SCUS-94163.bin
/gaadata/4/SCUS-94165.cue
/gaadata/4/SCUS-94163.cue
/gaadata/4/SCUS-94164.cue
/gaadata/4/SCUS-94163.png
/gaadata/4/SCUS-94164.bin
/gaadata/4/SCUS-94165.bin
/gaadata/9
/gaadata/9/pcsx.cfg
/gaadata/9/SLUS-01111.bin
/gaadata/9/SLUS-01111.lic
/gaadata/9/9
/gaadata/9/SLUS-01111.cue
/gaadata/9/SLUS-01111.png
/gaadata/16
/gaadata/16/pcsx.cfg
/gaadata/16/SCUS-94240.cue
/gaadata/16/SCUS-94240.bin
/gaadata/16/16
/gaadata/16/SCUS-94240.png
/gaadata/16/SCUS-94240.lic
/gaadata/20
/gaadata/20/pcsx.cfg
/gaadata/20/SCUS-94608.bin
/gaadata/20/SCUS-94608.cue
/gaadata/20/20
/gaadata/20/SCUS-94608.lic
/gaadata/20/SCUS-94608.png
/gaadata/15
/gaadata/15/pcsx.cfg
/gaadata/15/SLUS-00418.lic
/gaadata/15/15
/gaadata/15/SLUS-00418.bin
/gaadata/15/SLUS-00418.png
/gaadata/15/SLUS-00418.cue
/gaadata/2
/gaadata/2/pcsx.cfg
/gaadata/2/SCES-00992.png
/gaadata/2/SCES-00992.lic
/gaadata/2/SCES-00992.cue
/gaadata/2/2
/gaadata/2/SCES-00992.bin
/gaadata/3
/gaadata/3/pcsx.cfg
/gaadata/3/SCES-00008.lic
/gaadata/3/SCES-00008.bin
/gaadata/3/SCES-00008.png
/gaadata/3/3
/gaadata/3/SCES-00008.cue
/gaadata/6
/gaadata/6/pcsx.cfg
/gaadata/6/SCUS-94181.bin
/gaadata/6/SCUS-94181.lic
/gaadata/6/6
/gaadata/6/SCUS-94181.cue
/gaadata/6/SCUS-94181.png
/gaadata/10
/gaadata/10/pcsx.cfg
/gaadata/10/SLES-00664.otf
/gaadata/10/SLES-00664.bin
/gaadata/10/SLES-00664.cue
/gaadata/10/10
/gaadata/10/SLES-00664.png
/gaadata/10/SLES-00664.lic
/gaadata/geninfo
/gaadata/geninfo/REGION
/gaadata/8
/gaadata/8/SLUS-00594.cue
/gaadata/8/pcsx.cfg
/gaadata/8/SLUS-00776.cue
/gaadata/8/SLUS-00594.lic
/gaadata/8/SLUS-00594.png
/gaadata/8/8
/gaadata/8/SLUS-00776.bin
/gaadata/8/SLUS-00594.bin
/gaadata/preferences
/gaadata/preferences/regional.pre
/gaadata/bios
/gaadata/7
/gaadata/7/pcsx.cfg
/gaadata/7/SCES-00003.bin
/gaadata/7/SCES-00003.lic
/gaadata/7/SCES-00003.cue
/gaadata/7/SCES-00003.png
/gaadata/7/7
/gaadata/system
/gaadata/system/bios
/gaadata/system/bios/romw.bin
/gaadata/system/bios/romJP.bin
/gaadata/13
/gaadata/13/pcsx.cfg
/gaadata/13/SLUS-00339.lic
/gaadata/13/SLUS-00339.png
/gaadata/13/SLUS-00339.bin
/gaadata/13/SLUS-00339.cue
/gaadata/13/13
/gaadata/19
/gaadata/19/pcsx.cfg
/gaadata/19/SCUS-94304.bin
/gaadata/19/SCUS-94304.lic
/gaadata/19/SCUS-94304.png
/gaadata/19/SCUS-94304.cue
/gaadata/19/19
/gaadata/18
/gaadata/18/pcsx.cfg
/gaadata/18/SLES-01136.lic
/gaadata/18/SLES-01136.cue
/gaadata/18/SLES-01136.bin
/gaadata/18/SLES-01136.png
/gaadata/18/SLES-01136.otf
/gaadata/18/18
/gaadata/12
/gaadata/12/pcsx.cfg
/gaadata/12/SLES-00969.bin
/gaadata/12/SLES-00969.cue
/gaadata/12/SLES-00969.otf
/gaadata/12/SLES-00969.lic
/gaadata/12/SLES-00969.png
/gaadata/12/12
/gaadata/11
/gaadata/11/pcsx.cfg
/gaadata/11/SLUS-00005.bin
/gaadata/11/SLUS-00005.cue
/gaadata/11/SLUS-00005.png
/gaadata/11/11
/gaadata/11/SLUS-00005.lic

**Comment by justMaku** [comment]
Can you try following the instructions from https://github.com/justMaku/gpghax/issues/20#issuecomment-445982511?

**Comment by ValionPride** [comment]
That worked, Thank you!

**Comment by ValionPride** [comment]
Michal,

 

That worked, thank you.

 

V/r

Wes

**Comment by justMaku** [comment]
There seems to be a bug in the uninstall script because it should do it automatically by itself, will have to investigate later.
