### ISSUE TITLE
Uninstall of GPGHAX not working

### ISSUE THREAD

**Issue by voodoochild718** [justMaku/gpghax#25]
hello.

I started with the gpghax. I went through the process of formatting the drive and setting it up on my classic. I went through the whole blinking light process. Then before I loaded my first game, I stumbled across the Bleemsync method and tried my hand at that process since it is considered safer. 

I could not get Bleemsync to work but thought since the gpghax was unsafe, I would install it. 

I can not get the system to blink and go black though my games show up on the load screen. The custom games option is still there and there isn't an install log on my usb flash drive....HELP!!

**Comment by justMaku** [comment]
Please reformat your usb drive or try with another one. If you can't get the lights to blink it means the tool didn't even have a chance to load and do it's work.

**Comment by voodoochild718** [comment]
thanks man. great work in building and contributing to all of us that wanted more from Sony and was disappointed.
