### ISSUE TITLE
Custom game showing

### ISSUE THREAD

**Issue by Player1Login** [justMaku/gpghax#29]

**Comment by ExSOLDIER1** [comment]
Are you using a compatible USB stick? If so, try reformatting and making sure it is labeled "SONY" (has to be all caps) and downloading the .zip of the uninstaller, once it is done, extract the files directly to the root of the USB (IE: If your USB is "D", then when you double click on that, it should have 3 folders (lolhack, databases and the one with numbers and letters mixed) along with a README file.

When all that is complete, plug the USB stick into the PS Classic (Making sure the Classic is NOT connected power wise). Then power on the system and you should see the white Sony logo, and a few seconds after the system will cut off. Remove the USB and power cycle the Classic (remove power cable and put it back in 10 seconds later). If everything worked, your USB drive should have AUTOMATICALLY created the Log files you are talking about. Hope this helps!

**Comment by Player1Login** [comment]
Thanks!
