### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by jaricma** [justMaku/gpghax#3]
I can not load it from usb, it does not load the custom game

**Comment by Melluish** [comment]
Hi,

I thought I'd just let you know that I got mine working. Turn the console off (so you have the orange light), then plug in the USB stick, then unplug the micro USB (power) cable so the system turns completely off, then plug it back in and turn on the console. Your game should now show up.

**Comment by justMaku** [comment]
Make sure that you use FAT32 and name the volume `SONY`
