### ISSUE TITLE
japan console game missing

### ISSUE THREAD

**Issue by wai6510** [justMaku/gpghax#6]
I'm using japan version console and when i installed the custom game, it can show the custom game but all original game are missing and just have us version title without game picture, please help

**Comment by ElMassman** [comment]
I made a fork for the Japanese version, hopefully that should work for you...
(https://github.com/ElMassman/gpghax )

**Comment by wai6510** [comment]
I ask my friend and backup the db file from his japan console and fixed alreasy, anyway thank you for your help

**Comment by abe1007** [comment]
Thanks. I've just had a same problem and nearly ruined my console. Thank you EIMassman for saving my day.

**Comment by justMaku** [comment]
I'm terribly sorry this happened to you, I wasn't aware JP consoles have different games on them, here's how to fix this:

https://github.com/justMaku/gpghax/issues/18#issuecomment-445759173
