### ISSUE TITLE
Game 8 won't work after trying to load an alternate cover...

### ISSUE THREAD

**Issue by FrenchyToasty** [justMaku/gpghax#7]
Stupid move on my part, created an "8" directory with an alternate cover with the slus-xxxx.png image. anyway to get the console to load from internal memory again?

**Comment by Shinigati** [comment]
Got a similar issue here myself, didn't wanna add any "extra" games cuz i misunderstood the semi brick warning so i renamed the 21 folder to 20 and now the game won't even boot even after restoring the db and initializing the console.

**Comment by justMaku** [comment]
I'm not exactly sure how this could happen, but I will try to help you two, but first I would need you to do one thing to fully assess the damage that has been done.

Please modify the `lolhack.sh` file to only contain:

```
#!/bin/sh
find / > /media/filelist.log
sync
```

Run that payload (please wait couple of seconds before unplugging the USB drive) and after that open the USB drive on PC. There should be a file named filelist.log there, please upload it's content to pastebin.com and paste the link there.

**Comment by Shinigati** [comment]
Had no choice but to upload the file, pastebin only supports up to 512kb for free users but the log file was almost 3mb but i hope this helps.
[filelist.log](https://github.com/justMaku/gpghax/files/2662764/filelist.log)

**Comment by justMaku** [comment]
Did you also modify the database? Or just renamed the directory and run the payload?

**Comment by Shinigati** [comment]
I just renamed the directory, i have also since restored the original database file without the "21" entry and it still does the same thing, i go to launch the game and it just flashes really quickly like it's trying to load but kicks back to the main menu.

**Comment by justMaku** [comment]
Try adding this to your `lolhack.sh`:

```
rm /gaadata/20/20
```

**Comment by Shinigati** [comment]
That seems to have fixed it, thank you :)

**Comment by justMaku** [comment]
@Shinigati amazing! That's really weird that this broke it, but ¯\\\_(ツ)_/¯ quality Sony engineering.

@FrenchyToasty then for you it would be:
```
rm /gaadata/8/8
```
