### ISSUE TITLE
how to add games?

### ISSUE THREAD

**Issue by whip28** [justMaku/gpghax#8]
Would you be able to have a tutorial with picture or video to understand the method.Car I understand absolutely nothing.

Thank you

**Comment by Shinigati** [comment]
"Disclaimer: this can brick your console. Don't use if you don't understand every piece of how it works."
It's pretty straightforward without video or pictures so if you don't know you're better off waiting for a more user friendly method like hakchi but for ps classic.

**Comment by whip28** [comment]
For his request for help I am visual and not by writing.

**Comment by johnnyq** [comment]
I would wait it out a Nice GUI interface should be accompanied by the beginning of next week

**Comment by Sanandreas21** [comment]
As mentioned above, read the disclaimer first.. found this on YouTube

https://youtu.be/bmcayWjPe_Y

**Comment by justMaku** [comment]
Use https://github.com/pathartl/BleemSync instead. This repo was never supposed to be used as anything more than a reference to other developers.
